# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_slideshows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='autoplay',
            field=models.BooleanField(default=True, help_text=b'Autoplay slideshow'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='items',
            field=models.SmallIntegerField(default=3, help_text=b'Display this many items at a time'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='lazy_load',
            field=models.BooleanField(default=False, help_text=b'Lazy load images'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='mousedrag',
            field=models.BooleanField(default=False, help_text=b'Allow mouse dragging'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='navigation',
            field=models.BooleanField(default=True, help_text=b'Show navigation'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='pagination',
            field=models.BooleanField(default=False, help_text=b'Show pagination'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='pagination_speed',
            field=models.IntegerField(default=1200, help_text=b'Pagination speed'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='scroll_per_page',
            field=models.BooleanField(default=False, help_text=b'Scroll per page (not per item)'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='slide_speed',
            field=models.IntegerField(default=500, help_text=b'When autoplaying, display with this delay (ms) between slides'),
        ),
    ]
